# Generated by Django 3.0.4 on 2020-06-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiniCaseApp', '0003_case_contract_contractdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractdetails',
            options={'verbose_name_plural': 'ContractDetails'},
        ),
    ]
